-- Phase 3 forward migration for the existing Supabase project.
--
-- This migration is additive: it preserves the existing 20 products and 12
-- inventory rows. It prepares the legacy tables for the reviewed historical
-- import and for FIFO allocation in a later migration.

begin;

alter table public.products
  add column if not exists is_active boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

alter table public.inventory_batches
  add column if not exists received_at date,
  add column if not exists remaining_quantity integer,
  add column if not exists cost_status text not null default 'known',
  add column if not exists raw_product_name text,
  add column if not exists source_workbook text,
  add column if not exists source_row integer;

-- Existing batch rows pre-date the import. Preserve their quantity as the
-- current remaining quantity until their actual stock position is reconciled.
update public.inventory_batches
set remaining_quantity = quantity
where remaining_quantity is null;

alter table public.inventory_batches
  alter column remaining_quantity set not null,
  alter column cost_price drop not null;

alter table public.inventory_batches
  drop constraint if exists inventory_batches_remaining_quantity_check,
  add constraint inventory_batches_remaining_quantity_check
    check (remaining_quantity >= 0 and remaining_quantity <= quantity),
  drop constraint if exists inventory_batches_cost_status_check,
  add constraint inventory_batches_cost_status_check
    check (cost_status in ('known', 'pending'));

alter table public.orders
  add column if not exists source_order_key text,
  add column if not exists source_sheet text,
  add column if not exists source_order_number integer,
  add column if not exists source_row integer,
  add column if not exists customer_link text,
  add column if not exists order_date date,
  add column if not exists date_precision text,
  add column if not exists date_source text,
  add column if not exists audit_status text,
  add column if not exists appointment_note text,
  add column if not exists shipping_status text,
  add column if not exists source_payment_text text,
  add column if not exists settlement_status text,
  add column if not exists order_adjustment numeric(12, 0) not null default 0,
  add column if not exists cost_status text not null default 'known',
  add column if not exists note text;

alter table public.orders
  alter column total_cost drop not null;

alter table public.orders
  drop constraint if exists orders_date_precision_check,
  add constraint orders_date_precision_check
    check (date_precision is null or date_precision in ('day', 'month')),
  drop constraint if exists orders_audit_status_check,
  add constraint orders_audit_status_check
    check (audit_status is null or audit_status in ('audited', 'unaudited')),
  drop constraint if exists orders_settlement_status_check,
  add constraint orders_settlement_status_check
    check (settlement_status is null or settlement_status in ('settled', 'not_reviewed')),
  drop constraint if exists orders_cost_status_check,
  add constraint orders_cost_status_check
    check (cost_status in ('known', 'pending'));

alter table public.order_items
  add column if not exists source_item_key text,
  add column if not exists raw_product_name text,
  add column if not exists base_unit_price numeric(12, 0),
  add column if not exists line_discount numeric(12, 0) not null default 0,
  add column if not exists cost_status text not null default 'known',
  add column if not exists price_source text;

alter table public.order_items
  alter column total_cost drop not null;

alter table public.order_items
  drop constraint if exists order_items_cost_status_check,
  add constraint order_items_cost_status_check
    check (cost_status in ('known', 'pending'));

create table if not exists public.inventory_allocations (
  id bigint generated by default as identity primary key,
  order_item_id integer not null references public.order_items(id),
  inventory_batch_id integer not null references public.inventory_batches(id),
  quantity integer not null check (quantity > 0),
  unit_cost numeric(12, 0) check (unit_cost >= 0),
  cost_status text not null default 'known' check (cost_status in ('known', 'pending')),
  created_at timestamptz not null default now(),
  unique (order_item_id, inventory_batch_id)
);

alter table public.inventory_allocations
  alter column unit_cost drop not null,
  add column if not exists cost_status text not null default 'known';

alter table public.inventory_allocations
  drop constraint if exists inventory_allocations_cost_status_check,
  add constraint inventory_allocations_cost_status_check
    check (cost_status in ('known', 'pending'));

create table if not exists public.payment_logs (
  id bigint generated by default as identity primary key,
  order_id integer not null references public.orders(id),
  payment_method text not null check (payment_method in ('cash', 'bank_transfer')),
  destination_account text,
  amount numeric(12, 0) not null check (amount > 0),
  paid_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (
    (payment_method = 'cash' and destination_account is null)
    or (payment_method = 'bank_transfer' and destination_account is not null)
  )
);

-- RLS is enabled with no browser/client policies yet. This keeps the database
-- private until Phase 4 provides a server-side data-access layer.
alter table public.products enable row level security;
alter table public.inventory_batches enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory_allocations enable row level security;
alter table public.payment_logs enable row level security;

create unique index if not exists orders_source_order_key_unique_idx
  on public.orders (source_order_key)
  where source_order_key is not null;

create unique index if not exists order_items_source_item_key_unique_idx
  on public.order_items (source_item_key)
  where source_item_key is not null;

create index if not exists inventory_batches_product_fifo_idx
  on public.inventory_batches (product_id, received_at, id)
  where remaining_quantity > 0 and received_at is not null;

create index if not exists order_items_order_id_idx
  on public.order_items (order_id);

create index if not exists order_items_product_id_idx
  on public.order_items (product_id);

create index if not exists inventory_allocations_order_item_id_idx
  on public.inventory_allocations (order_item_id);

create index if not exists payment_logs_order_id_idx
  on public.payment_logs (order_id);

create index if not exists orders_order_date_idx
  on public.orders (order_date);

commit;
