-- Preserve an audit trail whenever an existing completed order is corrected.
create table if not exists public.order_change_logs (
  id bigint generated by default as identity primary key,
  order_id integer not null references public.orders(id),
  before_data jsonb not null,
  after_data jsonb not null,
  change_note text,
  changed_at timestamptz not null default now()
);

alter table public.order_change_logs enable row level security;

create index if not exists order_change_logs_order_id_idx
  on public.order_change_logs (order_id, changed_at desc);
